global:
  scrape_interval: 15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. Default is every 1 minute.

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'fastapi_app'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['app:8000']

  - job_name: 'postgres_exporter_0'
    static_configs:
      - targets: ['postgres-exporter-0:9187']

  - job_name: 'postgres_exporter_1'
    static_configs:
      - targets: ['postgres-exporter-1:9187']

  - job_name: 'postgres_exporter_2'
    static_configs:
      - targets: ['postgres-exporter-2:9187']

  - job_name: 'redis_exporter'
    static_configs:
      - targets: ['redis-exporter:9121']

  - job_name: 'redpanda'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['redpanda:9644'] # Redpanda's default Prometheus metrics port
  
  - job_name: 'worker'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['worker:8001'] # Worker metrics port
